<?php
/*
If you have installed the script in the root of the http server, which is usually
the "public_html" folder on shared web hostings, you might not need to edit this
file at all.
If you have it installed on a sub-domain, it would most probably be a sub-folder
inside the "public_html" folder.
Please do not edit this file without knowledge about your host server.
*/

$GLOBALS['DocRoot'] = $_SERVER['DOCUMENT_ROOT'];
/* In most cases, Document root would work just fine.
 * If it doesn't though, you would need to use an absolute path, like
 * $GLOBALS['DocRoot'] = "/home/u456789/public_html/";
 */

$GLOBALS['RootApp'] = "";
/*
 * Leave this empty if the script is installed in the server root.
 * If you have installed in a subfolder instead like
 * http://c0mmand0.in/site/folder/
 * You would need to put the folders and subfolders seperated with "/" like
 * $GLOBALS['RootApp'] = "site/folder";
 */

 //Do not edit the following line
 $GLOBALS['DocRoot'] .= "/" ;//. $GLOBALS['RootApp'] . "/";


 //The name of the theme to use
 //Edit this only if you have created a new theme
$GLOBALS['currTheme'] = "Theme01";
 ?>
